version: '3'

services:
    sql-server:
        image: mcr.microsoft.com/mssql/server
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password1234
            - MSSQL_PID=Developer
        ports:
            - "1430:1433"
        container_name: sql-server
    volumes:
        - sqlvolume:/var/opt/mssql

volumes:
    sqlvolume:
    